IA/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r"^$", views.login_redirect,name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls', namespace='accounts')),
    url(r'^home/', include('home.urls', namespace='home')),
]

accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
    login, logout, password_reset, password_reset_done, password_reset_confirm,
    password_reset_complete
)

urlpatterns = [
    url(r'^login/$',login, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', logout, {'template_name': 'accounts/logout.html'}, name='logout'),
    url(r'^register/$',views.register, name='register'),
    url(r'^profile/$',views.view_profile, name='view_profile'),
    url(r'^profile/edit/$',views.edit_profile, name='edit_profile'),
    url(r'^change-password/$',views.change_password, name='change_password'),

    url(r'^reset-password/$', password_reset,{'template_name': 'accounts/reset_password.html',
                                              'post_reset_redirect':'accounts:password_reset_done'},
        name='reset_password'),

    url(r'^reset-password/done/$', password_reset_done,name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,
        name='password_rest_confirm'),
    url(r'^reset-password/complete/$', password_reset_complete,name='password_reset_complete'),
]

home/urls.py
from django.conf.urls import url
from  views import HomeView
urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home')
]

accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


# Create your models here.
#class UserProfileManager(models.Manager):
#    def get_queryset(self):
#        return super(UserProfileManager, self).get_queryset().filter(city='balasore')

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    description = models.CharField(max_length=200,default='')
    city = models.CharField(max_length=200,default='')
    website = models.URLField(max_length=200,default='')
    phone = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

home/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Post(models.Model):
    post = models.CharField(max_length=500)
    user = models.ForeignKey(User)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm


class RegistartionForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self,commit= True):
        user = super(RegistartionForm,self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user


class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'email',
            'password'
        )

home/forms.py
from django import forms
from models import Post

class HomeForm(forms.ModelForm):
    post = forms.CharField()

    class Meta:
        model = Post
        fields = ('post',)

IA/views.py
from django.shortcuts import redirect

def login_redirect(request):
    return redirect('/account/login')

accounts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,redirect,HttpResponse
from .forms import (
    RegistartionForm,
    EditProfileForm,
)
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required

# Create your views here.

def register(request):
    if request.method == 'POST':
        form = RegistartionForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/account')
    else:
        form = RegistartionForm()

        args = {'form': form}
        return render(request, 'accounts/reg_form.html', args)


def view_profile(request):
    args = {'user': request.user}
    return render(request, 'accounts/profile.html', args)

def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('/account/profile')
    else:
        form= EditProfileForm(instance=request.user)

        args = {'form': form}
        return render(request,'accounts/edit_profile.html',args)

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('/account/profile/')
        else:
            return redirect('/account/change-password/')

    else:
        form= PasswordChangeForm(user=request.user)

        args = {'form': form}
        return render(request,'accounts/change_password.html',args)

home/views.py
from django.views.generic import TemplateView
from django.shortcuts import render
from forms import HomeForm
from models import Post

class HomeView(TemplateView):
    template_name = 'home/home.html'

    def get(self, request):
        form = HomeForm()
        posts = Post.objects.all().order_by('-created')

        args = {'form': form ,'posts':posts}
        return render(request, self.template_name, args)

    def post(self, request):
        form = HomeForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            text = form.cleaned_data['post']
            form = HomeForm()

        args = {'form': form, 'text':text}
        return render(request, self.template_name, args)

accounts/templates/accounts/change_password.html
{%extends "base.html" %}

{% block head %}
    <title>Change Password!</title>
{% endblock %}

{% block body %}
   <form method="POST">
       {% csrf_token %}
       {{ form.as_p }}
       <button type="submit">Submit</button>
   </form>

{% endblock %}

accounts/templates/accounts/edit_profile.html
{%extends "base.html" %}

{% block head %}
    <title>Edit Profile!</title>
{% endblock %}

{% block body %}
   <form method="POST">
       {% csrf_token %}
       {{ form.as_p }}
       <button type="submit">Submit</button>
   </form>

{% endblock %}

accounts/templates/accounts/login.html
{%extends "base.html" %}

{% block head %}
    <title>Login!</title>
{% endblock %}

{% block body %}
<div class="container">
    <h1>Welcome</h1>
    <h2>You can login here</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/logout.html
{%extends "base.html" %}

{% block head %}
    <title>Logedout!</title>
{% endblock %}

{% block body %}
<div class="container">
    <h1>Welcome</h1>
    <h2>You have loged out</h2>

</div>
{% endblock %}

accounts/templates/accounts/profile.html
{%extends "base.html" %}

{% block head %}
    <title>Profile!</title>
{% endblock %}

{% block body %}
    <h2>Profile</h2>
    <p>UserName: {{ user }}</p>
    <p>First Name: {{ user.first_name }}</p>
    <p>Last Name: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
    <p>Description: {{ user.userprofile.description }}</p>

   <a href="{% url 'accounts:edit_profile' %}"><button>Edit</button></a>

{% endblock %}

accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}

{% block body %}
<div class="'container">
    <h1>Registration</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</div>

{% endblock %}

accounts/templates/accounts/reset_password.html
{%extends "base.html" %}

{% block head %}
    <title>Login!</title>
{% endblock %}

{% block body %}
<div class="container">
    <h1>Password Reset</h1>
    <h2>You can reset your password here</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset Password</button>
    </form>
</div>
{% endblock %}

accounts/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        {% block head %}
        <meta charset="utf-8">
        <title>Base</title>
        {% endblock %}
    </head>
    <body>
        <br>
        <div class="container">

      <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">IA Project</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
              {% if user.is_authenticated %}
              <ul class="nav navbar-nav navbar-left">
                  <li><a href="{% url 'home:home' %}">Home</a></li>
                  <li><a href="{% url 'accounts:view_profile' %}">Profile</a></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                  <li><a href="{% url 'accounts:edit_profile' %}">Edit Profile</a></li>
                  <li><a href="{% url 'accounts:change_password' %}">Change Password</a></li>
                  <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
              </ul>
             {% else %}
              <ul class="nav navbar-nav navbar-left">
                  <li><a href="{% url 'accounts:reset_password' %}">Reset Password</a></li>
              </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'accounts:login' %}">Login</a></li>
              <li><a href="{% url 'accounts:register' %}">Register</a></li>
            </ul>
              {% endif %}
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>
    <!-- /container -->
        {% block body %}
        {% endblock %}
    </div>
    </body>
</html>

home/templates/home/home.html
{% extends "base.html" %}

{% block body %}
    <h1>Its Working!!</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    {% for post in posts %}
    <h1>{{post.post}}</h1>
    <p>Posted by {{post.user.get_full_name}} on {{ post.created}}</p>
    {% endfor %}
{% endblock %}